[package]
name = "rscms"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.17.0"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
mongodb = "3.2.3"
chrono = "0.4"
