name: Build and Deploy

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rscms:latest -f Dockerfile .
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rscms:latest

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 43.134.91.85
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /data/wwwroot/rscms
            docker pull docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rscms:latest
            docker compose down
            docker compose up -d
